porting tests to macOS pipeline (WIP)

diff --git a/.github/workflows/macos_testing.yml b/.github/workflows/macos_testing.yml
--- a/.github/workflows/macos_testing.yml
+++ b/.github/workflows/macos_testing.yml
@@ -12,6 +12,11 @@ on:
   #    - setups/setup_cloud_clients.sh
   #    - setups/setup_utils.sh
   workflow_dispatch:
+    inputs:
+      debug_enabled:
+        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
+        required: false
+        default: 'false'
 
 jobs:
   testingMacOS1015:
@@ -52,10 +57,20 @@ jobs:
       shell: bash
       run: |
         cd tests
-        bash packages.sh
-        zsh -i -c ./workspaces.sh
-        zsh -i -c ./utils.sh
-        zsh -i -c ./cloud_clients.sh
+        echo "Preventing compinit to fail due to bad zsh dir permissions"
+        sudo chmod 755 /usr/share/zsh
+        sudo chmod 755 /usr/share/zsh/vendor-completions
+        echo "Running test scripts involving zsh shell"
+        script -e -c 'zsh -i -c ./workspaces.sh'
+        script -e -c 'zsh -i -c ./utils.sh'
+        script -e -c 'zsh -i -c ./cloud_clients.sh'
+    - name: Setup tmate session
+      uses: mxschmitt/action-tmate@v3
+      if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled != 'false') || failure() }}
+      #timeout-minutes: 30
+      with:
+        sudo: true  # default
+        limit-access-to-actor: true  # allow ssh access to keys loaded in GitHub
   testingMacOS11:
     name: scripts on macOS 11 Big Sur
     runs-on: macos-11
@@ -94,10 +109,20 @@ jobs:
       shell: bash
       run: |
         cd tests
-        bash packages.sh
-        zsh -i -c ./workspaces.sh
-        zsh -i -c ./utils.sh
-        zsh -i -c ./cloud_clients.sh
+        echo "Preventing compinit to fail due to bad zsh dir permissions"
+        sudo chmod 755 /usr/share/zsh
+        sudo chmod 755 /usr/share/zsh/vendor-completions
+        echo "Running test scripts involving zsh shell"
+        script -e -c 'zsh -i -c ./workspaces.sh'
+        script -e -c 'zsh -i -c ./utils.sh'
+        script -e -c 'zsh -i -c ./cloud_clients.sh'
+    - name: Setup tmate session
+      uses: mxschmitt/action-tmate@v3
+      if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled != 'false') || failure() }}
+      #timeout-minutes: 30
+      with:
+        sudo: true  # default
+        limit-access-to-actor: true  # allow ssh access to keys loaded in GitHub
   sendNotification:
     name: Send Notification
     runs-on: ubuntu-20.04
